version: '3.8'
services:
  db:
    image: postgres:13
    restart: always
    container_name: auth-starter-db
    environment:
      - POSTGRES_USER=authStarter
      - POSTGRES_PASSWORD=authStarter
      - POSTGRES_DB=authStarter
    ports:
      - '5000:5432'